import Head from "next/head";
import { useEffect } from "react";
import Navbar from "./Navbar";
import { useRouter } from "next/router";
import NProgress from "nprogress";
const Layout = ({ title, children }) => {
  const router = useRouter();
  useEffect(() => {
    const handleRouteChange = (url) => {
      console.log(url);
      NProgress.start();
    };
    router.events.on("routeChangeStart", handleRouteChange);

    router.events.on("routeChangeComplete", () => NProgress.done());

    return () => {
      router.events.off("routeChangeStart", handleRouteChange);
    };
  }, []);
  return (
    <div className="bg-zinc-900 w-full h-auto min-h-screen text-white">
      <Head>
        <title>John | {title ? title : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css"
          integrity="sha512-42kB9yDlYiCEfx2xVwq0q7hT4uf26FUgSIZBK8uiaEnTdShXjwr8Ip1V4xGJMg3mHkUt9nNuTDxunHF0/EgxLQ=="
          crossOrigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Navbar />
      <div className="w-full px-48 py-24">{children}</div>
      <footer className="w-full px-12">
        &copy; {new Date().getFullYear()} John
      </footer>
    </div>
  );
};
export default Layout;
